### ISSUE TITLE
MinVersion requirements is 1.3.7 in manifest.json

### ISSUE THREAD

**Issue by peterzhu1992** [kelszo/obsidian-file-explorer-plus#1]
I see you set the minVersion to 1.3.7, so I cannot use it on my setup as I have a stable 1.3.5 and have no intention to upgrade soon.

Just wondering is this a typo or it has to be on 1.3.7 to work?
https://github.com/kelszo/obsidian-file-explorer-plus/blob/master/manifest.json

Thanks.

**Comment by kelszo** [comment]
Yeah sorry about that. I will loosen that restriction.

The explanation was that I was actually waiting for Obsidian 1.4.0 to release with its better support for tags. Currently, tags written in the frontmatter are not parsed and added to the cache API. However, I realised that might take some time so I went for the latest stable version.

**Comment by kelszo** [comment]
Fixed with latest release, new min app version is now 0.15.0 (seems to be default for most plugins).

**Comment by peterzhu1992** [comment]
Thanks very much!
