### ISSUE TITLE
Filter stopped working after applying workspace layout

### ISSUE THREAD

**Issue by Accelsnow** [kelszo/obsidian-file-explorer-plus#18]
### What happened?

After I apply the workspace layouts, toggling the hide filter has no effect on file explorer display.

### What did you expect to happen?

Toggling the hide filter should always hide/display the filtered files/folders regardless of whether a workspace layout has been applied or not.

### Can you reproduce the bug, if so how? As detailed but minimal as possible.

Yes.
1. create a hide filter that filters out some folder/files
2. apply the filter. The folders/files will be correctly hidden.
3. Apply a workspace layout
4. Try disabling the hide filter. The hidden folders/files do not re-appear.

### Other?

I noticed that when I apply workspace layout, the file explorer seems to have changed style a little bit (slightly smaller margin it seems). I am wondering if the file explorer is reloaded during the process, but File-Explorer-Plus is still on an old instance of the explorer (Disclaimer: I have no knowledge of obsidian plugin, just a genuine guess).
Restarting obsidian does fix the problem. It will correctly display whatever state the filter was at time of exit.

### Plugin version

1.1.4

### Obsidian version

1.5.12

### OS

Windows

**Comment by kelszo** [comment]
For a genuine guess I think it is a very good one, that is most likely the case. I will try to replicate and get back to you

**Comment by kelszo** [comment]
Should be fixed with latest plugin version. Re-open if not.
