### ISSUE TITLE
Wish I was able to hide certain files by extension type e.g. hide PNG attachments

### ISSUE THREAD

**Issue by itoldusoandso** [kelszo/obsidian-file-explorer-plus#20]
### What would you like to be added?

For example I want to hide PNG files from the File Explorer pane in Obsidian.
Tried with a variety of expressions for the filter but nothing worked.

### Why is this needed?

Want to be able to hide certain file types.

**Comment by kelszo** [comment]
See #8.

Trying the wildcard filter `**/*.png` should work. 

 I see this is a common problem that the way filters work are not documented enough. I will update the README to provide some good examples (#15).

Please close this issue if the above filter works.

**Comment by itoldusoandso** [comment]
Thank you. I will close it now. Don't know if it solves it. 

Found another solution around by moving all attachments to subfolders within the folders and then I am hiding the subfolders so the attachments do not show up anymore.
