### ISSUE TITLE
Unhide files

### ISSUE THREAD

**Issue by gerroon** [kelszo/obsidian-file-explorer-plus#4]
### What would you like to be added?

Hi

I accidentally hid a file now I cant find the file in the explorer, naturally. I see that I can see them in the plugins settings page under hidden files path filter but there does not seem to be away to unhide them :( 

### Why is this needed?

Because the file can't be made visible back. Having the list of hidden files is helpful but it does not help with unhiding them.

**Comment by kelszo** [comment]
Make sure the “Hide strict path filters in settings” is off, so you see all filters. Remove or deactivate the filter that is hiding your file
