### ISSUE TITLE
There is no setting option to hide files by name.

### ISSUE THREAD

**Issue by DanShui-Yu** [kelszo/obsidian-file-explorer-plus#8]
### What happened?

The introduction states "Flexibility in Filtering: Hide and pin files and folders using wildcard or regex filters for names, paths, and tags," but in fact, the settings only include tag filters and path filters.

![image](https://github.com/kelszo/obsidian-file-explorer-plus/assets/69069739/4c8295ce-6de0-4302-a47f-675199641dbc)

### What did you expect to happen?

I would like to have name filters that allow me to freely set specific extension types of files to automatically hide.

### Can you reproduce the bug, if so how? As detailed but minimal as possible.

I'm a new user who is currently searching for a solution to meet the aforementioned requirement. When I downloaded from the plugin market, this is what I encountered.

### Plugin version

1.1.4

### Obsidian version

1.5.8

### OS

Windows

**Comment by kelszo** [comment]
This is already possible. The "Path Filter" includes the file name, i.e. if you set a filter to hide "*.pdf" (I recommend looking into the wildcard syntax), it will hide all PDF files. If you set a filter to "File To Hide", it will hide all notes that have the name "File To Hide", independent of what folder they are in.

Please close this issue if this works for you, or if you need further explanation don't hesitate to ask :)

**Comment by DanShui-Yu** [comment]
Thank you for your response. I tried to hide all `.edtz` files using `*.edtz`, but after setting it up, only the `.edtz` files in the root directory were hidden, and those in other folders were not.

![image](https://github.com/kelszo/obsidian-file-explorer-plus/assets/69069739/d3f592c0-42fc-43cf-b1ff-0da718e29a52)

**Comment by kelszo** [comment]
Sorry, I was unclear before. As per the wildcard syntax you will have to do this to hide edtz files in all directories: `**/*.edtz`.

** is meant for matching files in subdirectories.
